### ISSUE TITLE
accessToken: "SUPER SECRET!!!",

### ISSUE THREAD

**Issue by ChiropracticBender** [zuo000/MMM-HomeAssistant#3]
What steps should i take to create this accessToken.

LegacyAPI password doesn't work and i've also tried trusted networks. 

i checked
https://developers.home-assistant.io/docs/auth_api/#refresh-token
and
https://www.home-assistant.io/docs/authentication/

**Comment by ChiropracticBender** [comment]
magicmirror config
```js
		{
			module: "MMM-HomeAssistant",
			position: "middle_center",
			config: {
				host: "http://hassio.local",
				port: 8123, // your HA port, 8123 by default.
				accessToken: "secret",
				updateInterval: 5*1000
			}
		},
```

home assistant
```yaml
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        192.168.1.64: 1234123
    - type: legacy_api_password
      api_password: !secret http_password```

**Comment by zuo000** [comment]
You can obtain a token ("Long-Lived Access Token") by logging into the frontend using a web browser.
steps:
1. log in your HA by browser.
2. click your name on the left bottom corner
3. scroll down to "Long-Lived Access Tokens" at bottom fo this page and click "Create Token"
